[build-system]
requires = ["setuptools>=65.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "multiphoton_guide"
version = "0.1.0"
description = "Multiphoton Microscopy Guide"
requires-python = ">=3.8" 