name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libgl1
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint and Reformat
        run: |
          black .
          isort .
          flake8 .
      - name: Test
        run: pytest -q
